# Generated by Django 3.2.6 on 2021-09-01 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='rPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post', verbose_name='Пост'),
        ),
    ]
